-- 브랜드 초기 데이터 삽입
INSERT INTO brands (name) VALUES
  ('Chasin'' Rabbits'),
  ('10 BRANDS'),
  ('2aN'),
  ('Abib'),
  ('ACWELL'),
  ('AGE20''S'),
  ('AMUSE'),
  ('ANOTHERFACE'),
  ('BANOBAGI'),
  ('BBIA'),
  ('BEIGIC'),
  ('BERRISOM'),
  ('BIOHEAL BOH'),
  ('BRING GREEN'),
  ('BRMUD'),
  ('BYNEWCELL'),
  ('Bywishtrend'),
  ('CELLFUSION C'),
  ('CENTELLIAN24'),
  ('COLORGRAM'),
  ('d''Alba'),
  ('DASHU'),
  ('Deardoer'),
  ('DearKlairs'),
  ('DELIGHT PROJECT'),
  ('Dermafirm'),
  ('DEWYTREE'),
  ('Dr.bio'),
  ('Dr.G'),
  ('DR.PEPTI'),
  ('EARTHAT'),
  ('EASYDEW'),
  ('EIOM'),
  ('ELROEL'),
  ('Epais'),
  ('FARMSKIN'),
  ('FARMSTAY'),
  ('Fation'),
  ('Foodology'),
  ('Frudia'),
  ('FWEE'),
  ('G9SKIN'),
  ('Gorilla Technique'),
  ('HAYEJIN'),
  ('HERBLOOM'),
  ('HOUSEOFB'),
  ('I''m from'),
  ('Illumiel'),
  ('It''s Skin'),
  ('iunik'),
  ('IWELL US'),
  ('JUNG KWAN JANG'),
  ('KAHI'),
  ('LABIT'),
  ('Lafeme'),
  ('LAKA'),
  ('LEMOUTON'),
  ('Lepique'),
  ('LILYEVE'),
  ('MARS MADE'),
  ('MAXCLINIC'),
  ('Medicube'),
  ('MEDIPEEL'),
  ('MIDHA'),
  ('Mixsoon'),
  ('MODAMODA'),
  ('My Normal'),
  ('NARD'),
  ('NEWMIX'),
  ('Nongshim'),
  ('NOON''S UP'),
  ('Numbuzin'),
  ('ODAC'),
  ('ODELOI'),
  ('One day''s you'),
  ('Overlaps'),
  ('Peach C'),
  ('PECTRUS'),
  ('Pinate'),
  ('PURCELL'),
  ('Purito Seoul'),
  ('Pyunkang yul'),
  ('RATED GREEN'),
  ('RAWQUEST'),
  ('Roastique'),
  ('ROM&ND'),
  ('SAM''U'),
  ('Self beauty'),
  ('SELFBEAUTY'),
  ('Signiq'),
  ('SKIN1004'),
  ('Smilebloom KKOCH'),
  ('Steambase'),
  ('THE A''VVE'),
  ('UNLIMEAT'),
  ('VEGREEN'),
  ('VT Cosmetics'),
  ('Vyneherb'),
  ('WAKE MAKE'),
  ('Withgear'),
  ('Yadah'),
  ('YUREE LAB'),
  ('The saem'),
  ('마녀공장'),
  ('SOMEBYMI'),
  ('Anillo'),
  ('Ancient to Today'),
  ('YUNJAC'),
  ('Fountain of Waters'),
  ('Pongdang')
ON CONFLICT (name) DO NOTHING;


